@ecommer_HostAddress = http://127.0.0.1:8000/api

# Register User
POST {{ecommer_HostAddress}}/user
Content-Type: application/json

{
	"email": "amaei@unn.edu.ng",
	"password": "Password1@",
	"confirm_password": "Password1@"
}
###

# Login User
POST {{ecommer_HostAddress}}/auth/login
Content-Type: application/json

{
	"email": "user2@gmail.com",
	"password": "Password@2"
}
###

POST {{ecommer_HostAddress}}/auth/logout
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTc5Nzc3LCJpYXQiOjE3NjQwOTMzNzcsImp0aSI6ImI1OGFkMjI5YjY5ODRhOTBhYzlkMzY1MTE2ZjBjZDBmIiwidXNlcl9pZCI6IjUyNmI3Y2M4LTM1YjYtNDUzMi1iNWZjLTE3Y2FiNzY5NzYxYyJ9.jqjrYEW6n7wKg8JNH1d2voIZjlL56JkbUp5Zstadb90
###

# Get Current User
GET {{ecommer_HostAddress}}/auth/user
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY0MTc5Nzc3LCJpYXQiOjE3NjQwOTMzNzcsImp0aSI6ImI1OGFkMjI5YjY5ODRhOTBhYzlkMzY1MTE2ZjBjZDBmIiwidXNlcl9pZCI6IjUyNmI3Y2M4LTM1YjYtNDUzMi1iNWZjLTE3Y2FiNzY5NzYxYyJ9.jqjrYEW6n7wKg8JNH1d2voIZjlL56JkbUp5Zstadb90
###

GET {{ecommer_HostAddress}}/vendor-only
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzYxMjMwMzY4LCJpYXQiOjE3NjEyMjkxNjgsImp0aSI6ImNkY2FlZWNlYzcxODQzNzdiODYxYTViNWQ2MmIxZjdkIiwidXNlcl9pZCI6ImYwZTFjN2FkLTM1NWEtNDdjMi04NDIwLTE2Y2M5OTE4OGNmZSJ9.esFXX0Va16k1t58sTzwXDFy6TDS9ujb99gMi1A4BJGo

###

GET {{ecommer_HostAddress}}/products/all
Content-Type: application/json

###

GET {{ecommer_HostAddress}}/products/details/4c62943f-e12f-4297-915d-9ef1f0281d7c
###

GET {{ecommer_HostAddress}}/health

###
GET {{ecommer_HostAddress}}/carts
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ0b2tlbl90eXBlIjoiYWNjZXNzIiwiZXhwIjoxNzY1OTcyMjE4LCJpYXQiOjE3NjU4ODU4MTgsImp0aSI6IjQ3M2U1Y2M1MWY5ZTRlNjNiZTAxNmJmMTZjNjc1OGU4IiwidXNlcl9pZCI6IjdmMzUxMjk5LTdlNmUtNGQ0MC1hYmNiLTBmODgxODVkMzBkYSJ9.FjXupel5qTqu1rF9fRWApZSfvaRQEfZJRItowf26HvI