# Generated by Django 5.2.7 on 2025-10-16 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('brand_name', models.CharField(max_length=128)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='venders')),
                ('is_activated', models.BooleanField(default=False)),
                ('total_sales_ever', models.DecimalField(decimal_places=2, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': 'Vendors',
                'db_table': 'vendors',
                'indexes': [models.Index(fields=['id'], name='vendors_id_a48508_idx')],
            },
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='users')),
                ('password', models.CharField(max_length=1024)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_customer', models.BooleanField(default=True)),
                ('is_vendor', models.BooleanField(default=False)),
                ('date_joined', models.DateTimeField(auto_now_add=True)),
                ('last_login', models.DateTimeField()),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'CustomUser',
                'verbose_name_plural': 'CustomUsers',
                'db_table': 'custom_users',
                'indexes': [models.Index(fields=['id'], name='custom_user_id_fec7a9_idx'), models.Index(fields=['email'], name='custom_user_email_c8f161_idx')],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=128)),
                ('stock', models.PositiveIntegerField(default=0)),
                ('description', models.TextField()),
                ('is_on_flash_sales', models.BooleanField(default=False)),
                ('current_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('old_price', models.DecimalField(decimal_places=2, max_digits=18)),
                ('thumbnail', models.ImageField(upload_to='products')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.vendor')),
            ],
            options={
                'db_table': 'products',
                'indexes': [models.Index(fields=['id'], name='products_id_5ad420_idx')],
            },
        ),
    ]
