# Generated by Django 5.2.7 on 2025-10-30 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_refrence',
            field=models.CharField(default='TXN-<function uuid4 at 0x000002A361119C60>', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(default='vend-b93657d8-a26b-41dd-9ca8-6afde39d879d', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='total_sales_ever',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
    ]
