# Generated by Django 5.2.7 on 2025-10-30 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_alter_order_payment_refrence_alter_vendor_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_refrence',
            field=models.CharField(default='TXN-<function uuid4 at 0x0000021A726C9C60>', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(default='vend-1b70964f-3ef2-477a-bca2-55c54b64048e', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
