# Generated by Django 5.2.7 on 2025-10-21 11:06

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_customuser_last_login'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('0a937898-e03a-4b29-9619-8405c6efe67b'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4af64aee-9f3e-4ecc-9fcc-b783ffb4a648'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(default='vend-c4be6a04-76f3-4408-897e-1798c0730b1e', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
