# Generated by Django 5.2.7 on 2025-10-30 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_order_payment_refrence_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_refrence',
            field=models.CharField(default='TXN-<function uuid4 at 0x00000211A2A49C60>', editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(default='vend-14844718-139c-4249-b0cd-559095e47cf0', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
