# Generated by Django 5.2.7 on 2025-10-21 11:49

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_customuser_id_alter_product_id_alter_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a343731e-698f-4b22-97c4-d9d74254c798'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.UUID('c37b9afa-eadc-4df4-aa9f-3ab1a3bfc3a8'), editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(default='vend-8e022f51-01d0-44bd-adfc-9376c966f852', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
