# Generated by Django 5.2.7 on 2025-10-30 16:06

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_order_payment_refrence_alter_product_stock_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='payment_refrence',
            field=models.CharField(default=core.models.gen_payment_ref, editable=False, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(default='vend-<function uuid4 at 0x000002E992D19C60>', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
    ]
