# Generated by Django 5.2.7 on 2025-10-28 11:25

import django.db.models.deletion
import django_resized.forms
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_customuser_id_alter_product_id_alter_vendor_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='thumbnail',
            field=django_resized.forms.ResizedImageField(crop=None, force_format=None, keep_meta=True, quality=-1, scale=None, size=[1920, 1080], upload_to='products'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='avatar',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=75, scale=None, size=[50, 50], upload_to='venders'),
        ),
        migrations.AlterField(
            model_name='vendor',
            name='id',
            field=models.CharField(default='vend-9d0451ce-afc8-4f6a-89d1-66d4c648262f', editable=False, max_length=50, primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('added_at', models.DateTimeField(auto_now_add=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cart_items', to='core.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Cart Items',
                'db_table': 'cart_items',
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('cart_items', models.ManyToManyField(related_name='carts', to='core.cartitem')),
            ],
            options={
                'verbose_name_plural': 'Carts',
                'db_table': 'cart',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('price_per_item', models.DecimalField(decimal_places=2, max_digits=18)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.product')),
            ],
            options={
                'verbose_name_plural': 'Order Items',
                'db_table': 'order_items',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('Processing', 'Processing'), ('Successful', 'Successful'), ('Cancelled', 'Cancelled'), ('Delivered', 'Delivered')], default='Processing', max_length=12)),
                ('amount', models.DecimalField(decimal_places=2, editable=False, max_digits=12)),
                ('payment_refrence', models.CharField(default='TXN-<function uuid4 at 0x0000025D97C59C60>', editable=False, max_length=50, unique=True)),
                ('transaction_refrence', models.CharField(blank=True, max_length=300)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('order_items', models.ManyToManyField(related_name='orders', to='core.orderitem')),
            ],
            options={
                'verbose_name': 'Order',
                'verbose_name_plural': 'Orders',
                'db_table': 'orders',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_method', models.CharField(blank=True, choices=[('Card', 'Card'), ('Bank Transfer', 'Bank Transfer'), ('USSD', 'USSD'), ('Wallet', 'Wallet')], max_length=50)),
                ('payment_status', models.CharField(choices=[('Intiated', 'Initiated'), ('Pending', 'Pending'), ('Successful', 'Successful'), ('Failed', 'Failed'), ('Refunded', 'Refunded'), ('Cancelled', 'Cancelled')], default='Intiated', max_length=50)),
                ('transaction_refrence', models.CharField(blank=True, editable=False, max_length=300, unique=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('order', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.order')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
                'db_table': 'payments',
            },
        ),
        migrations.CreateModel(
            name='ShippingAddress',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=150)),
                ('last_name', models.CharField(max_length=150)),
                ('phone', models.CharField(help_text='+234', max_length=16)),
                ('address', models.CharField(max_length=150)),
                ('country', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=150)),
                ('lga', models.CharField(max_length=150)),
                ('zip_code', models.CharField(max_length=10)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Shipping Addresses',
                'db_table': 'shipping_addresses',
            },
        ),
        migrations.AddField(
            model_name='order',
            name='shipp_addr',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.shippingaddress'),
        ),
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['id'], name='cart_items_id_a34a6d_idx'),
        ),
        migrations.AddIndex(
            model_name='cart',
            index=models.Index(fields=['id'], name='cart_id_32fa18_idx'),
        ),
        migrations.AddIndex(
            model_name='orderitem',
            index=models.Index(fields=['id'], name='order_items_id_2b4eeb_idx'),
        ),
        migrations.AddIndex(
            model_name='payment',
            index=models.Index(fields=['id'], name='payments_id_71f414_idx'),
        ),
        migrations.AddIndex(
            model_name='shippingaddress',
            index=models.Index(fields=['id'], name='shipping_ad_id_fe415d_idx'),
        ),
        migrations.AddIndex(
            model_name='order',
            index=models.Index(fields=['id'], name='orders_id_ddf884_idx'),
        ),
    ]
